stages:
  - PreTest
  - Build

variables:
  VERSION: "0.8.0"

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

.build_image: &build_image
  script:
    - docker build --build-arg "VERSION=$VERSION" -f Dockerfile -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker run --rm $CI_REGISTRY_IMAGE:$VERSION -version
    - docker push $CI_REGISTRY_IMAGE:$VERSION
  tags:
    - docker-build

golang-lint:
  stage: PreTest
  script:
    - docker pull golangci/golangci-lint:latest
    - docker run --rm -v "$PWD":/app -w /app golangci/golangci-lint:latest golangci-lint --color always run

image build and push:
  <<: *build_image
  stage: Build
  only:
    - master
  tags:
    - docker-build
