before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

.build_image: &build_image
  script:
    - docker build --build-arg "VERSION=$VERSION" -f Dockerfile -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
  only:
    - master
  tags:
    - docker-build

build image:
  <<: *build_image
  variables:
    VERSION: "v0.5.0"
